# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    assignees: ["frasermolyneux"]
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:15"
      timezone: "Etc/UTC"
    groups:
      all-updates:
        patterns:
          - "*"
    ignore:
      - dependency-name: "Microsoft.ApplicationInsights*"
        versions: [">=3.0.0"]
      - dependency-name: "Nerdbank.GitVersioning"
        versions: [">=3.10.0"]

  - package-ecosystem: "github-actions"
    assignees: ["frasermolyneux"]
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:15"
      timezone: "Etc/UTC"
    groups:
      all-updates:
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    assignees: ["frasermolyneux"]
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:15"
      timezone: "Etc/UTC"
    groups:
      all-updates:
        patterns:
          - "*"