# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    assignees: ["frasermolyneux"]
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:15"
      timezone: "Etc/UTC"
    groups:
      nuget:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    assignees: ["frasermolyneux"]
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:15"
      timezone: "Etc/UTC"
    groups:
      github-actions:
        patterns:
          - "*"