parameters:
- name: jobName
  type: string
  default: BuildNetProject
- name: dependsOn
  type: object
  default: []
- name: solutionName
  type: string
  default: 'solution'
- name: MajorMinorVersion
  type: string
  default: '1.0'
- name: nugetConfigPath
  type: string
  default: ''

jobs:
- job: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.dependsOn }}

  variables:
    buildConfiguration: 'Release'
    buildPlatform: 'Any CPU'
    version: '2.3.0.$(Build.BuildId)'

  steps:
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/${{ parameters.solutionName }}.sln'
      command: 'restore'
      ${{ if ne(parameters.nugetConfigPath, '') }}:
        feedsToUse: 'config'
        nugetConfigPath: ${{ parameters.nugetConfigPath }}

  - task: MSBuild@1
    inputs:
      solution: '**/${{ parameters.solutionName }}.sln'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      msbuildArguments: '/target:publish /p:ApplicationVersion=$(version) /p:ProductName="XI Demo Manager" /p:PublishDir="$(build.artifactStagingDirectory)\\" /p:PublishURL=https://demomanagerclient.blob.core.windows.net/versions/ /p:UpdateEnabled=true /p:UpdateMode=Foreground'