parameters:
- name: azureSubscription
  type: string
- name: environment
  type: string
- name: environmentName
  type: string

stages:
- stage: deploy_${{ parameters.environmentName }}
  jobs:
  - deployment: deploy_${{ parameters.environmentName }}_platform
    environment: ${{ parameters.environment }}

    workspace:
      clean: all

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              displayName: deploy_${{ parameters.environmentName }}_platform_bicep
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  $config = (Get-Content params/platform.${{ parameters.environmentName }}.json | ConvertFrom-Json)

                  az deployment sub create `
                    --name "demo-manager-platform-$($config.parameters.parEnvironment.value)-$($config.parameters.parInstance.value)" `
                    --template-file bicep/platform.bicep `
                    --location $config.parameters.parEnvironment.value `
                    --parameters @params/platform.$($config.parameters.parEnvironment.value).json

            - task: AzureCLI@2
              displayName: DeployPlatformPermissions
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                addSpnToEnvironment: true
                inlineScript: |
                  $config = (Get-Content params/platform.${{ parameters.environmentName }}.json | ConvertFrom-Json)

                  $spn = (az ad sp show --id $env:servicePrincipalId) | ConvertFrom-Json

                  $storageAccount = (az storage account show --resource-group "rg-demo-manager-$($config.parameters.parEnvironment.value)-$($config.parameters.parLocation.value)-$($config.parameters.parInstance.value)" `
                    --name $($config.parameters.parStorageAccountName.value)) | ConvertFrom-Json

                  az role assignment create --assignee $spn.appId --role 'Storage Blob Data Contributor' --scope $storageAccount.id | Out-Null


  - deployment: deploy_${{ parameters.environmentName }}_artifact
    dependsOn: ['deploy_${{ parameters.environmentName }}_platform']
    environment: ${{ parameters.environment }}

    workspace:
      clean: all

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - download: current
              displayName: 'Download DemoManager artifact'
              artifact: DemoManager

            - task: AzureCLI@2
              displayName: CopyArtifact
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                addSpnToEnvironment: true
                inlineScript: |
                  $config = (Get-Content params/platform.${{ parameters.environmentName }}.json | ConvertFrom-Json)

                  az storage blob upload-batch --destination versions --source $(Pipeline.Workspace)/DemoManager --account-name $($config.parameters.parStorageAccountName.value)) --auth-mode login --overwrite
