trigger: none
pr: none

pool: 'Dedicated'

resources:
  pipelines:
  - pipeline: demo-manager.Validate
    source: demo-manager.Validate
    trigger:
      branches:
        include:
        - main

stages: 
- stage: Build
  jobs:
  - template: templates/build-demomanager-solution.yml
    parameters: 
      solutionName: 'DemoManager'
      publishArtifact: true


- stage: DeployPrdPlatform

  jobs:
  - deployment: DeployPlatformBicep
    environment: 'demomanager-prd'

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              displayName: DeployPlatformBicep
              inputs:
                azureSubscription: 'spn-ado-XtremeIdiots-Public-xtremeidiots-demomanager-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  if ($null -eq (az keyvault show --name 'kv-demomgr-prd-uksouth')) { $keyVaultCreateMode = 'default' } else { $keyVaultCreateMode = 'recover' }

                  az deployment sub create `
                    --template-file bicep/platform.bicep `
                    --location uksouth `
                    --parameters @params/platform.prd.json `
                      parKeyVaultCreateMode=$keyVaultCreateMode

            - task: AzureCLI@2
              displayName: DeployPlatformPermissions
              inputs:
                azureSubscription: 'spn-ado-XtremeIdiots-Public-xtremeidiots-demomanager-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                addSpnToEnvironment: true
                inlineScript: |
                  $spn = (az ad sp show --id $env:servicePrincipalId) | ConvertFrom-Json
                  $storageAccount = (az storage account show --resource-group rg-demomanager-prd-uksouth --name demomanagerclient) | ConvertFrom-Json
                  az role assignment create --assignee $spn.appId --role 'Storage Blob Data Contributor' --scope $storageAccount.id | Out-Null

- stage: DeployPrdArtifact

  jobs:
  - deployment: DeployPrdArtifact
    environment: 'demomanager-prd'

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - download: current
              displayName: 'Download DemoManager artifact'
              artifact: DemoManager

            - task: AzureCLI@2
              displayName: CopyArtifact
              inputs:
                azureSubscription: 'spn-ado-XtremeIdiots-Public-xtremeidiots-demomanager-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                addSpnToEnvironment: true
                inlineScript: |
                  az storage blob upload-batch --destination versions --source $(Pipeline.Workspace)/DemoManager --account-name demomanagerclient --auth-mode login --overwrite
