trigger: none
pr: none

pool: 'Dedicated'

resources:
  pipelines:
  - pipeline: demo-manager.Validate
    source: demo-manager.Validate
    trigger:
      branches:
        include:
        - main

stages: 
- stage: Build
  jobs:
  - template: templates/build-demomanager-solution.yml
    parameters: 
      solutionName: 'DemoManager'
      publishArtifact: true