trigger: none
pr: none

pool: 'Dedicated'

resources:
  pipelines:
  - pipeline: demo-manager.Validate
    source: demo-manager.Validate
    trigger:
      branches:
        include:
        - main

stages: 
- stage: Build
  jobs:
  - template: templates/build-demomanager-solution.yml
    parameters: 
      solutionName: 'DemoManager'
      publishArtifact: true

- stage: Deploy
  jobs:
    - download: current
      displayName: 'Download DemoManager artifact'
      artifact: DemoManager

    - task: AzureFileCopy@4
      inputs:
        SourcePath: '$(Pipeline.Workspace)/DemoManager/*'
        azureSubscription: 'spn-ado-XtremeIdiots-Public-xtremeidiots-demomanager-prd'
        Destination: 'AzureBlob'
        storage: 'demomanagerclient'
        ContainerName: 'versions'