parameters:
- name: keyVaultCreateMode
  type: string
  default: recover
  values:
  - 'recover'
  - 'default'

trigger: none
pr: none

pool: 'Dedicated'

resources:
  pipelines:
  - pipeline: demo-manager.Validate
    source: demo-manager.Validate
    trigger:
      branches:
        include:
        - main

stages: 
- stage: Build
  jobs:
  - template: templates/build-demomanager-solution.yml
    parameters: 
      solutionName: 'DemoManager'
      publishArtifact: true


- stage: DeployPrdPlatform

  jobs:
  - deployment: DeployPlatformBicep
    environment: 'demomanager-prd'

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              displayName: DeployPlatformBicep
              inputs:
                azureSubscription: 'spn-ado-XtremeIdiots-Public-xtremeidiots-demomanager-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub create `
                    --template-file bicep/platform.bicep `
                    --location uksouth `
                    --parameters @params/platform.prd.json parKeyVaultCreateMode '${{ parameters.keyVaultCreateMode }}'

- stage: DeployPrdArtifact

  jobs:
  - deployment: DeployPrdArtifact
    environment: 'demomanager-prd'

    strategy:
      runOnce:
        deploy:
          steps:

            - download: current
              displayName: 'Download DemoManager artifact'
              artifact: DemoManager

            - task: AzureFileCopy@4
              inputs:
                SourcePath: '$(Pipeline.Workspace)/DemoManager/*'
                azureSubscription: 'spn-ado-XtremeIdiots-Public-xtremeidiots-demomanager-prd'
                Destination: 'AzureBlob'
                storage: 'demomanagerclient'
                ContainerName: 'versions'
