trigger:
  branches:
    include:
      - main

pr:
  autoCancel: true
  branches:
    include:
      - main

schedules:
  - cron: "0 2 * * 4"
    displayName: "Weekly Security Scan (Thu 02:00 UTC)"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

stages:
  - stage: build
    jobs:
      - template: jobs/devops-secure-scanning.yml@ado-pipeline-templates
