trigger:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pr:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

variables:
  buildConfiguration: 'Release'

stages: 
- stage: build
  jobs:

  #- template: jobs/dependency-check.yml@ado-pipeline-templates
  #  parameters: 
  #    jobName: 'DependencyCheck'
  #    failOnCVSS: 4

  - template: templates/build-demomanager-solution.yml
    parameters: 
      solutionName: 'DemoManager'
      publishArtifact: true

  - template: jobs/bicep-lint-code.yml@ado-pipeline-templates
    parameters: 
      jobName: 'bicep_linter'
      azureSubscription: spn-demo-manager-production

  - template: templates/bicep-environment-validation.yml
    parameters:
      dependsOn: [bicep_linter]
      azureSubscription: spn-demo-manager-production
      environment: demo-manager-Production
      environmentName: 'prd'

- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  - template: templates/deploy-environment.yml
    parameters:
      azureSubscription: spn-demo-manager-production
      environment: demo-manager-Production
      environmentName: 'prd'
