trigger:
  branches:
    include:
    - main
    - feature/*
    - dependabot/*

pr:
  branches:
    include:
    - main
    - feature/*
    - dependabot/*

schedules:
  - cron: "0 3 * * 0"
    displayName: Weekly Build
    branches:
      include:
      - main

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

pool: 'Dedicated'

stages: 
- stage: Build
  jobs:
  - template: jobs/dependency-check.yml@ado-pipeline-templates
    parameters: 
      jobName: 'DependencyCheck'
      failOnCVSS: 4

  - template: templates/build-demomanager-solution.yml
    parameters: 
      solutionName: 'DemoManager'
