trigger:
  branches:
    include:
    - main
    - feature/*
    - dependabot/*

pr:
  branches:
    include:
    - main
    - feature/*
    - dependabot/*

schedules:
  - cron: "0 3 * * 0"
    displayName: Weekly Build
    branches:
      include:
      - main

pool: 'Dedicated'

stages: 
- stage: Build
  jobs:
  - template: templates/dependency-check.yml
    parameters: 
      jobName: 'DependencyCheck'
      failOnCVSS: 4

  - template: templates/build-demomanager-solution.yml
    parameters: 
      solutionName: 'DemoManager.App'