name: PR Verify

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

permissions: {}

jobs:
  build-and-test:
    permissions:
      contents: read
    if: github.event.pull_request.draft == false
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Set up NuGet
        uses: NuGet/setup-nuget@v4

      - name: Restore NuGet packages
        shell: pwsh
        run: |
          Set-Location "${{ github.workspace }}\src"
          nuget restore "DemoManager.sln"

      - name: Build solution
        shell: pwsh
        run: |
          Set-Location "${{ github.workspace }}\src"
          msbuild "DemoManager.sln" /p:Configuration=Release /p:Platform="Any CPU"

  terraform-plan-prd:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    environment: Production
    concurrency:
      group: ${{ github.repository }}-prd
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
    steps:
      - uses: frasermolyneux/actions/terraform-plan@terraform-plan/v1.4
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/prd.tfvars"
          terraform-backend-file: "backends/prd.backend.hcl"
          AZURE_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ env.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
